# Generated by Django 5.0.7 on 2024-08-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    (
                        "can_change_product_description",
                        "Can change product description",
                    ),
                    ("can_change_product_category", "Can change product category"),
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
